[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[cursor]
style = "Beam"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrains Mono"

[font.italic]
family = "JetBrains Mono"

[font.normal]
family = "JetBrains Mono"
size = 15
style = "ExtraLight"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[mouse.hint.launcher]
program = "firefox-developer-edition"

[window]
auto_scroll = false
decorations = "none"
opacity = 0.8
size = 14.0
startup_mode = "Fullscreen"

[window.padding]
x = 5
y = 0
